# Disable color and theme in dumb/basic terminals. 
if [[ "$TERM" == 'dumb' || "$TERM" == "linux" ]]; then
   zstyle ':zsh' color 'no'
   zstyle ':zsh:prompt' theme 'off'
fi

export EDITOR="emacs -nw"
export PAGER="less"

[ -z "$HOSTNAME" ] && export HOSTNAME="$(hostname)"

if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

HISTSIZE=25000
SAVEHIST="${HISTSIZE}"

fpath=(~/.zsh/completion $fpath)

autoload -Uz compinit promptinit add-zsh-hook
compinit
promptinit

autoload -U select-word-style
select-word-style bash

prompt suse
if [[ $+commands[pista] ]]; then
 _pista_prompt() {                
        PROMPT="%n@%m: $(pista -zm)"
 }
 add-zsh-hook precmd _pista_prompt
fi

setopt cdablevars
setopt checkjobs
setopt autocd
setopt HISTSAVENODUPS
setopt HISTFINDNODUPS
setopt pushdignoredups 
setopt append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history 
setopt extended_history

if [[ $+commands[rbenv] ]]; then
  eval "$(rbenv init -)"
fi

for zshrc_file in $HOME/.zsh/zsh/*.zsh; do
  source $zshrc_file
done



PATH="/home/lonstein/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/lonstein/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/lonstein/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/lonstein/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/lonstein/perl5"; export PERL_MM_OPT;
