# Disable color and theme in dumb/basic terminals. 
if [[ "$TERM" == 'dumb' || "$TERM" == "linux" ]]; then
   zstyle ':zsh' color 'no'
   zstyle ':zsh:prompt' theme 'off'
fi

export EDITOR="emacs"
export PAGER="less"

[ -z "$HOSTNAME" ] && export HOSTNAME="$(hostname)"

if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

HISTSIZE=25000
SAVEHIST="${HISTSIZE}"

fpath=(~/.zsh/completion $fpath)

autoload -Uz compinit promptinit
compinit
promptinit

prompt suse

setopt cdablevars
setopt checkjobs
setopt autocd
setopt HISTSAVENODUPS
setopt HISTFINDNODUPS
setopt pushdignoredups 
setopt append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history 
setopt extended_history

if [[ -n `which rbenv` ]]; then
  eval "$(rbenv init -)"
fi

for zshrc_file in $HOME/.zsh/*.zsh; do
  source $zshrc_file
done


